# Generated by Django 5.1.3 on 2024-11-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apto',
            name='apto',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apto',
            name='condominio',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
