# Generated by Django 5.1.3 on 2024-11-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_apto_apto_apto_condominio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apto',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
