# Generated by Django 5.1.3 on 2024-11-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_apto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apto',
            name='tel',
            field=models.CharField(max_length=16),
        ),
    ]
