# Generated by Django 5.1.3 on 2024-11-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_apto_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('morador', models.CharField(max_length=255)),
                ('condominio', models.CharField(max_length=255)),
                ('apto', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('recebeu', models.BooleanField(default=False)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('tipo', models.IntegerField(choices=[(1, 'Correspondência'), (2, 'Encomenda')])),
                ('status', models.BooleanField(default=True)),
                ('comando', models.IntegerField()),
            ],
        ),
    ]
